stages:
  prepare_data:
    cmd: Rscript Code/prep.R
    deps:
      - Code/prep.R
      - Rawdata/articles.csv
      - Rawdata/transactions_train.csv
      - Rawdata/images/
     
    outs:
      - Data/processed_articles.parquet

  
      
  



